pipelineJob('FFE_Decommissioning_Pipeline') {
  description ('description FFE Decommissioning Job - autogenerated using JobDSL - all manual changes will be overwritten!')
    logRotator {
        numToKeep(100)
    }
    parameters {
         stringParam{
            name('project_name')
            defaultValue('')
            description('Name of OpenStack Project')
            trim(true)
        }
        stringParam{
            name('jira_ticket')
            defaultValue('')
            description('Demand management ticket associated with deployment (eg. EEDS-XXXX) A notification of the FFE decommission will be left as a comment on the ticket provided')
            trim(true)
        }
    }
    definition {
        cpsScm {
          scm {
            git {
              branch('master')
              remote {
                credentials('lciadm100_gerrit_ssh')
                url("${GERRIT_MIRROR}/OSS/ENM-Parent/SQ-Gate/com.ericsson.de/openstack-kgb-pipelines")
              }
              extensions {
                cleanBeforeCheckout()
              }
        	}
          }
          scriptPath('FFE/Jenkinsfiles/FFE_Decommissioning_Pipeline.groovy')
          lightweight(lightweight = true)
        }
    }
}